---
- hosts: localhost
  connection: local
  tasks: 
    - name: Create a resource
      azure_rm_resourcegroup:
        name: table2kbansibletest
        location: canadaeast
        tags: 
          testing: testing
          delete: never
