---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
  - name: Delete Resource Group
    azure_rm_resourcegroup:
      name: "{{group_name}}"
      state: absent
      force: true
