- name: Create VM in RG
  hosts: localhost
  connection: local
  vars:
    rg: table2kbvmrg
    vnet: table2kbvnet
    subnet: table2kbsubnet
    ip: table2kbpublicip
    sg: table2kbsggroup
    nic: table2kbnic
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{rg}}"
      location: canadaeast
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{rg}}" 
      name: "{{vnet}}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{rg}}"
      name: "{{subnet}}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{vnet}}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{rg}}"
      allocation_method: Static
      name: "{{ip}}"
    register: output_ip_address
  - name: Output public IP 
    debug:
      msg: "Public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{rg}}" 
      name: "{{sg}}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{rg}}"
      name: "{{nic}}"
      virtual_network: "{{vnet}}"
      subnet: "{{subnet}}"
      public_ip_name: "{{ip}}"
      security_group: "{{sg}}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{rg}}"
      name: table2kbvm
      vm_size: Standard_DS1_v2
      admin_username: azureops
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureops/.ssh/authorized_keys
          key_data: |
            {{ lookup('file','/home/azureops/.ssh/id_rsa.pub') }}
      network_interfaces: "{{nic}}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
  - name: Install Apache
    apt:
      pkg: apache2
      state: present
      update_cache: true
