- hosts: localhost
  connection: local
  vars:
    group: table2kbwebapprg
    webapp_name: table2kbwebapp
    location: canadaeast
  tasks:
    - name: create rg
      azure_rm_resourcegroup:
        name: "{{group}}"
        location: "{{location}}"
        state: absent
        force: true
