- hosts: localhost
  connection: local
  vars:
    group: table2kbwebapprp
    webapp_name: table2kbwebapp
    location: canadaeast
 tasks:
   - name: create rg
     azure_rm_resourcegroup:
       name: "{{group}}"
       location: "{{location}}"
   - name: Create App Service
     azure_rm_webapp:
       resource_group: "{{group}}"
       name: "{{webapp_name}}"
       plan:  
         resource_group: "{{group}}"
         name: table2kbappplan
         is_linux: true
         sku: S1
         number_of_workers: 1       
